### ISSUE TITLE
[LO add-on] Crash with today's nightly - 2022-08-04

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#6992]
Hello @FredKruse 

I downloaded the nightly minutes ago and when I right-clicked in Portuguese marked words it crashed:
![LT_crash_20220804](https://user-images.githubusercontent.com/5192600/182923051-b4f0cf53-4bb3-4f29-96ae-dae3685560e5.png)

**Comment by marcoagpinto** [comment]
ahhhh… I closed LibreOffice and reopened it, and now right-clicking in these marked words doesn't work.

I have LibreOffice 7.4.0.2.

**Comment by FredKruse** [comment]
The bug should be solved by the tomorrow nightly.

**Comment by marcoagpinto** [comment]
@FredKruse 

I have installed 2022-08-06 and now, when I right-click on marked words, LibreOffice hangs (document is in Portuguese).

**Comment by FredKruse** [comment]
This could be related to a problem with tables. Please test it with the next nightly tomorrow.

**Comment by FredKruse** [comment]
There were still some problems with view cursor handling. Possibly, that causes the fails. Please test it with tomorrow snapshot 20220809.

**Comment by marcoagpinto** [comment]
@FredKruse 

LibreOffice still hangs when I right-clicked in an underlined word.

Tested with the latest nightly.

**Comment by FredKruse** [comment]
@marcoagpinto Could you send me a example text? But it will take at least a weak. I'm not at home.

**Comment by marcoagpinto** [comment]
I tried to get an example text, so I removed all I could from my gigantic thesis, and it didn't hang.

So, I am unable to provide a sample.

😭

**Comment by marcoagpinto** [comment]
@FredKruse 

I have been trying to get a sample document.

In my tries, I got a LanguageTool crash:
![crash_lt_20220810](https://user-images.githubusercontent.com/5192600/183863282-969346dd-2664-4c37-8a91-134b02f3179d.png)

**Comment by marcoagpinto** [comment]
Here is a sample that causes it.
[crash_sample_20220810.odt](https://github.com/languagetool-org/languagetool/files/9298683/crash_sample_20220810.odt)

**Comment by marcoagpinto** [comment]
@FredKruse 

!!!!
